Repository bitwyre/sdk, pull requests merged in 2021-09, with the labels that each got.

#27 fix(sdk): conan build process
  cpp/conanfile.py
  cpp/source/CMakeLists.txt
  cpp/source/rest/public/Time.hpp
  cpp/source/unittest/publicApi.test.cpp
Labels: size/S

#29 feat(async-sdk-cpp): resign all added async features to source/rest/public
  README.md
  cpp/README.md
  cpp/source/rest/public/Announcements.hpp
  cpp/source/rest/public/Asset.hpp
  cpp/source/rest/public/Contract.hpp
  cpp/source/rest/public/CryptoAsset.hpp
  cpp/source/rest/public/Depth.hpp
  cpp/source/rest/public/FiatAsset.hpp
  cpp/source/rest/public/Instrument.hpp
  cpp/source/rest/public/Market.hpp
  cpp/source/rest/public/OrderTypes.hpp
  cpp/source/rest/public/Product.hpp
  cpp/source/rest/public/SupportedLanguages.hpp
  cpp/source/rest/public/Ticker.hpp
  cpp/source/rest/public/Time.hpp
  cpp/source/unittest/publicApi.test.cpp
Labels: size/XL

#30 should be `testmain.cpp` in line 7 cmakelist for unitest
  cpp/source/unittest/CMakeLists.txt
Labels: size/XS

#31 feat(async-sdk-cpp): added all async features to source/rest/private
  .gitignore
  cpp/source/details/Dispatcher.hpp
  cpp/source/rest/private/AccountBalance.hpp
  cpp/source/rest/private/AccountStatement.hpp
  cpp/source/rest/private/CancelOrder.hpp
  cpp/source/rest/private/ClosedOrders.hpp
  cpp/source/rest/private/NewOrder.hpp
  cpp/source/rest/private/OpenOrders.hpp
  cpp/source/rest/private/OrderInfo.hpp
  cpp/source/rest/private/TradesHistory.hpp
  cpp/source/rest/private/TransactionHistory.hpp
  cpp/source/rest/public/Announcements.hpp
  cpp/source/rest/public/Contract.hpp
  cpp/source/rest/public/CryptoAsset.hpp
  cpp/source/rest/public/Depth.hpp
  cpp/source/rest/public/FiatAsset.hpp
  cpp/source/rest/public/Product.hpp
  cpp/source/rest/public/SupportedLanguages.hpp
  cpp/source/rest/public/Ticker.hpp
  cpp/source/rest/public/Time.hpp
  cpp/source/rest/public/Trades.hpp
  cpp/source/unittest/MockAsyncDispatcher.hpp
  cpp/source/unittest/privateApi.test.cpp
  cpp/source/unittest/publicApi.test.cpp
  cpp/source/version.cpp.in
Labels: size/XL

#32 feat(maven project): initial commit
  .gitignore
  java/.classpath
  java/.gitignore
  java/.project
  java/pom.xml
  java/src/main/java/com/bitwyre/sdk/App.java
  java/src/main/java/com/bitwyre/sdk/PrivateAPI.java
  java/src/main/java/com/bitwyre/sdk/PublicAPI.java
  java/src/main/java/com/bitwyre/sdk/config.java
  java/src/test/java/com/bitwyre/sdk/AppTest.java
Labels: size/XXL

#34 feat(maven project): initial commit (#32)
  .gitignore
  java/.classpath
  java/.gitignore
  java/.project
  java/pom.xml
  java/src/main/java/com/bitwyre/sdk/App.java
  java/src/main/java/com/bitwyre/sdk/PrivateAPI.java
  java/src/main/java/com/bitwyre/sdk/PublicAPI.java
  java/src/main/java/com/bitwyre/sdk/config.java
  java/src/test/java/com/bitwyre/sdk/AppTest.java
Labels: size/XXL

#35 feat(maven project): read base_url+uri_path from config
  java/src/main/java/com/bitwyre/sdk/PrivateAPI.java
Labels: size/M

#36 feat(async-sdk-cpp): added callbacks for all public&private (without unit tests)
  .gitignore
  cpp/source/rest/private/AccountBalance.hpp
  cpp/source/rest/private/AccountStatement.hpp
  cpp/source/rest/private/CancelOrder.hpp
  cpp/source/rest/private/ClosedOrders.hpp
  cpp/source/rest/private/NewOrder.hpp
  cpp/source/rest/private/OpenOrders.hpp
  cpp/source/rest/private/OrderInfo.hpp
  cpp/source/rest/private/TradesHistory.hpp
  cpp/source/rest/private/TransactionHistory.hpp
  cpp/source/rest/public/Announcements.hpp
  cpp/source/rest/public/Asset.hpp
  cpp/source/rest/public/Contract.hpp
  cpp/source/rest/public/CryptoAsset.hpp
  cpp/source/rest/public/Depth.hpp
  cpp/source/rest/public/FiatAsset.hpp
  cpp/source/rest/public/Instrument.hpp
  cpp/source/rest/public/Market.hpp
  cpp/source/rest/public/OrderTypes.hpp
  cpp/source/rest/public/Product.hpp
  cpp/source/rest/public/SupportedLanguages.hpp
  cpp/source/rest/public/Ticker.hpp
  cpp/source/rest/public/Time.hpp
  cpp/source/rest/public/Trades.hpp
  cpp/source/unittest/MockAsyncDispatcher.hpp
  cpp/source/unittest/privateApi.test.cpp
  cpp/source/unittest/publicApi.test.cpp
Labels: size/L

#37 feat(kotlin sdk): add config, public api & gradle
  kotlin/build.gradle.kts
  kotlin/gradle.properties
  kotlin/gradle/wrapper/gradle-wrapper.jar
  kotlin/gradle/wrapper/gradle-wrapper.properties
  kotlin/gradlew
  kotlin/gradlew.bat
  kotlin/settings.gradle.kts
  kotlin/src/main/kotlin/com/bitwyre/kotlin_sdk/Config.kt
  kotlin/src/main/kotlin/com/bitwyre/kotlin_sdk/PublicAPI.kt
  kotlin/src/main/kotlin/test.kt
Labels: size/XL

#39 feat(c++/async api): callbacks and tests
  cpp/README.md
  cpp/conanfile.py
  cpp/source/rest/private/AccountBalance.hpp
  cpp/source/rest/private/AccountStatement.hpp
  cpp/source/rest/private/CancelOrder.hpp
  cpp/source/rest/private/ClosedOrders.hpp
  cpp/source/rest/private/NewOrder.hpp
  cpp/source/rest/private/OpenOrders.hpp
  cpp/source/rest/private/OrderInfo.hpp
  cpp/source/rest/private/TradesHistory.hpp
  cpp/source/rest/private/TransactionHistory.hpp
  cpp/source/rest/public/Asset.hpp
  cpp/source/rest/public/Contract.hpp
  cpp/source/rest/public/CryptoAsset.hpp
  cpp/source/rest/public/Depth.hpp
  cpp/source/rest/public/FiatAsset.hpp
  cpp/source/rest/public/Instrument.hpp
  cpp/source/rest/public/Market.hpp
  cpp/source/rest/public/OrderTypes.hpp
  cpp/source/rest/public/Product.hpp
  cpp/source/rest/public/SupportedLanguages.hpp
  cpp/source/rest/public/Ticker.hpp
  cpp/source/rest/public/Time.hpp
  cpp/source/rest/public/Trades.hpp
  cpp/source/unittest/MockAsyncDispatcher.hpp
  cpp/source/unittest/privateApi.test.cpp
  cpp/source/unittest/publicApi.test.cpp
Labels: size/L
