Repository bitwyre/sdk, pull requests merged in 2021-12, with the labels that each got.

#47 fix(utils.py): hack
  python/bitwyre_sdk/utils.py
Labels: size/XS

#49 fix(python): cancel per order ids
  python/bitwyre_sdk/__init__.py
Labels: size/S

#51 feat(rust-sdk):add config
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/config.rs
  rust/src/main.rs
Labels: size/M
