Repository bitwyre/sdk, pull requests merged in 2022-02, with the labels that each got.

#57 feat(rust-sdk): remove hardcoded symbols + additional private api
  rust/src/main.rs
  rust/src/private.rs
  rust/src/public/config.rs
Labels: size/L

#58 fix(rust-sdk): sync open + cancel order private api
  rust/src/main.rs
  rust/src/private.rs
Labels: size/L

#55 feat(rust-sdk): public async APIs
  rust/.gitignore
  rust/Cargo.lock
  rust/Cargo.toml
  rust/README.md
  rust/src/main.rs
  rust/src/private.rs
  rust/src/public.rs
  rust/src/public/config.rs
Labels: size/L

#60 test(rust-sdk): async API unit tests.
  rust/.cargo/config.toml
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/main.rs
  rust/src/private.rs
  rust/src/public.rs
  rust/src/public/config.rs
  rust/src/tests.rs
Labels: size/XXL

#61 test(rust-sdk): public async API integration tests
  rust/.cargo/config.toml
  rust/Cargo.lock
  rust/Cargo.toml
  rust/src/lib.rs
  rust/src/public/config.rs
  rust/tests/public.rs
Labels: size/L

#63 feat(python): add pagination
  python/bitwyre_sdk/__init__.py
Labels: size/M

#64 refactor(rust-sdk): async APIs return JSON string.
  rust/src/main.rs
  rust/src/private.rs
  rust/src/public.rs
  rust/tests/private.rs
  rust/tests/public.rs
Labels: size/XL
